//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsProjesi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DestekMesajlari
    {
        public int ID { get; set; }
        public Nullable<int> DestekBildirimID { get; set; }
        public Nullable<int> KullaniciID { get; set; }
        public Nullable<int> MusteriID { get; set; }
        public string Mesaj { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
    
        public virtual DestekBildirimler DestekBildirimler { get; set; }
        public virtual Kullanici Kullanici { get; set; }
        public virtual Musteri Musteri { get; set; }
    }
}
