//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsProjesi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DestekBildirimler
    {
        public DestekBildirimler()
        {
            this.DestekMesajlari = new HashSet<DestekMesajlari>();
        }
    
        public int ID { get; set; }
        public Nullable<int> DestekKategoriID { get; set; }
        public Nullable<int> MusteriID { get; set; }
        public Nullable<int> IsID { get; set; }
        public string Konu { get; set; }
        public string Icerik { get; set; }
        public string Dosya { get; set; }
        public Nullable<int> Durum { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
    
        public virtual DestekKategori DestekKategori { get; set; }
        public virtual Isler Isler { get; set; }
        public virtual Musteri Musteri { get; set; }
        public virtual ICollection<DestekMesajlari> DestekMesajlari { get; set; }
    }
}
