//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsProjesi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EvrakTur
    {
        public EvrakTur()
        {
            this.Evrak = new HashSet<Evrak>();
        }
    
        public int ID { get; set; }
        public string Adi { get; set; }
    
        public virtual ICollection<Evrak> Evrak { get; set; }
    }
}
