//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsProjesi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FirmaFaturaBilgi
    {
        public int ID { get; set; }
        public string Unvan { get; set; }
        public string Adres { get; set; }
        public string VergiDairesi { get; set; }
        public string VergiNumarasi { get; set; }
        public string Logo { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
    }
}
