//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsProjesi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Firma
    {
        public Firma()
        {
            this.BankaHesapBilgisi = new HashSet<BankaHesapBilgisi>();
        }
    
        public int ID { get; set; }
        public Nullable<int> IlceID { get; set; }
        public Nullable<int> ilID { get; set; }
        public string Adi { get; set; }
        public string Email { get; set; }
        public string Telefon { get; set; }
        public string Fax { get; set; }
        public string Yetkili { get; set; }
        public string Gsm { get; set; }
        public string Adres { get; set; }
    
        public virtual ICollection<BankaHesapBilgisi> BankaHesapBilgisi { get; set; }
        public virtual il il { get; set; }
        public virtual ilce ilce { get; set; }
    }
}
