//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsProjesi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GelirFatura
    {
        public GelirFatura()
        {
            this.GelirFatura_Detay = new HashSet<GelirFatura_Detay>();
            this.GelirOdeme = new HashSet<GelirOdeme>();
        }
    
        public int ID { get; set; }
        public Nullable<int> MusteriID { get; set; }
        public Nullable<int> SatisSiparisID { get; set; }
        public Nullable<double> ToplamTutar { get; set; }
        public Nullable<double> ToplamKdv { get; set; }
        public string Durum { get; set; }
        public Nullable<System.DateTime> OlusumTarihi { get; set; }
        public Nullable<System.DateTime> FaturaTarih { get; set; }
        public Nullable<System.DateTime> SonOdemeTarih { get; set; }
        public string OdemeDurum { get; set; }
    
        public virtual ICollection<GelirFatura_Detay> GelirFatura_Detay { get; set; }
        public virtual GelirFatura GelirFatura1 { get; set; }
        public virtual GelirFatura GelirFatura2 { get; set; }
        public virtual Musteri Musteri { get; set; }
        public virtual SatisSiparis SatisSiparis { get; set; }
        public virtual ICollection<GelirOdeme> GelirOdeme { get; set; }
    }
}
