//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsProjesi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GenelTasarimAyarlari
    {
        public int ID { get; set; }
        public string IndexLogo { get; set; }
        public string loginLogo { get; set; }
        public string PanelLogo { get; set; }
        public string FavikonIkon { get; set; }
        public string Ikon { get; set; }
        public string AcilisBaslik { get; set; }
        public string YoneticiGirisBaslik { get; set; }
        public string YoneticiPanelBaslik { get; set; }
        public string MusteriGirisBaslik { get; set; }
        public string MusteriPanelBaslik { get; set; }
        public string Renk1 { get; set; }
        public string Renk2 { get; set; }
        public string IndexArkaplanResim { get; set; }
        public string YoneticiArkaplanResim { get; set; }
        public string MusteriArkaPlanResim { get; set; }
        public string FaturaAltBilgi { get; set; }
        public string SiparisUstBilgi { get; set; }
        public string SiparisAltBilgi { get; set; }
        public string MailTasarimi { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
    }
}
