//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsProjesi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiderFatura
    {
        public GiderFatura()
        {
            this.GiderFatura_Detay = new HashSet<GiderFatura_Detay>();
            this.GiderOdeme = new HashSet<GiderOdeme>();
        }
    
        public int ID { get; set; }
        public Nullable<int> SatinAlmaSiparisID { get; set; }
        public Nullable<int> TedarikciID { get; set; }
        public Nullable<decimal> ToplamTutar { get; set; }
        public Nullable<decimal> KdvToplam { get; set; }
        public Nullable<System.DateTime> FaturaTarih { get; set; }
        public Nullable<System.DateTime> SonOdemeTarih { get; set; }
        public Nullable<System.DateTime> FaturaOlusumTarihi { get; set; }
        public string Durum { get; set; }
        public string OdemeDurumu { get; set; }
    
        public virtual SatinAlmaSiparis SatinAlmaSiparis { get; set; }
        public virtual ICollection<GiderFatura_Detay> GiderFatura_Detay { get; set; }
        public virtual Tedarikci Tedarikci { get; set; }
        public virtual ICollection<GiderOdeme> GiderOdeme { get; set; }
    }
}
