//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsProjesi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class il
    {
        public il()
        {
            this.Firma = new HashSet<Firma>();
            this.ilce = new HashSet<ilce>();
            this.Tedarikci = new HashSet<Tedarikci>();
        }
    
        public int ID { get; set; }
        public string Adi { get; set; }
    
        public virtual ICollection<Firma> Firma { get; set; }
        public virtual ICollection<ilce> ilce { get; set; }
        public virtual ICollection<Tedarikci> Tedarikci { get; set; }
    }
}
