//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsProjesi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kullanici
    {
        public Kullanici()
        {
            this.DestekMesajlari = new HashSet<DestekMesajlari>();
            this.KullaniciYetki = new HashSet<KullaniciYetki>();
        }
    
        public int ID { get; set; }
        public string Adi { get; set; }
        public string Soyadi { get; set; }
        public string Email { get; set; }
        public string Parola { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
    
        public virtual ICollection<DestekMesajlari> DestekMesajlari { get; set; }
        public virtual ICollection<KullaniciYetki> KullaniciYetki { get; set; }
    }
}
