//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsProjesi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MusteriAdaylari
    {
        public MusteriAdaylari()
        {
            this.SatisTalep = new HashSet<SatisTalep>();
            this.SatisTeklif = new HashSet<SatisTeklif>();
        }
    
        public int ID { get; set; }
        public Nullable<int> IlceID { get; set; }
        public string FirmaAdi { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public string Eposta { get; set; }
        public string Telefon { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public string Adres { get; set; }
        public Nullable<bool> Durum { get; set; }
    
        public virtual ilce ilce { get; set; }
        public virtual ICollection<SatisTalep> SatisTalep { get; set; }
        public virtual ICollection<SatisTeklif> SatisTeklif { get; set; }
    }
}
