//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsProjesi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Musteri
    {
        public Musteri()
        {
            this.DestekBildirimler = new HashSet<DestekBildirimler>();
            this.DestekMesajlari = new HashSet<DestekMesajlari>();
            this.Evrak = new HashSet<Evrak>();
            this.GelirFatura = new HashSet<GelirFatura>();
            this.Isler = new HashSet<Isler>();
            this.Not = new HashSet<Not>();
            this.PosBilgisi = new HashSet<PosBilgisi>();
            this.SatisSiparis = new HashSet<SatisSiparis>();
            this.SatisTalep = new HashSet<SatisTalep>();
            this.SatisTeklif = new HashSet<SatisTeklif>();
        }
    
        public int ID { get; set; }
        public Nullable<int> IlceID { get; set; }
        public Nullable<int> YetkiID { get; set; }
        public string FirmaAdi { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public string Eposta { get; set; }
        public string Telefon { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public string Adres { get; set; }
        public string Gsm { get; set; }
        public string Parola { get; set; }
        public string FaturaUnvan { get; set; }
        public string FaturaAdres { get; set; }
        public string VergiDairesi { get; set; }
        public string VergiNo { get; set; }
        public Nullable<bool> Durum { get; set; }
        public Nullable<int> IletisimDurumu { get; set; }
    
        public virtual ICollection<DestekBildirimler> DestekBildirimler { get; set; }
        public virtual ICollection<DestekMesajlari> DestekMesajlari { get; set; }
        public virtual ICollection<Evrak> Evrak { get; set; }
        public virtual ICollection<GelirFatura> GelirFatura { get; set; }
        public virtual ilce ilce { get; set; }
        public virtual ICollection<Isler> Isler { get; set; }
        public virtual Yetki Yetki { get; set; }
        public virtual ICollection<Not> Not { get; set; }
        public virtual ICollection<PosBilgisi> PosBilgisi { get; set; }
        public virtual ICollection<SatisSiparis> SatisSiparis { get; set; }
        public virtual ICollection<SatisTalep> SatisTalep { get; set; }
        public virtual ICollection<SatisTeklif> SatisTeklif { get; set; }
    }
}
