//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsProjesi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SatinAlmaBankaHesapBilgisi
    {
        public int ID { get; set; }
        public Nullable<int> SatinAlmaTedarikID { get; set; }
        public string BankaAdi { get; set; }
        public string BankaSube { get; set; }
        public string ParaBirimi { get; set; }
        public string HesapNo { get; set; }
        public string Durumu { get; set; }
        public string IbanNo { get; set; }
    
        public virtual Tedarikci Tedarikci { get; set; }
    }
}
