//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsProjesi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SatinAlmaSiparis_Detay
    {
        public string ID { get; set; }
        public Nullable<int> SatinAlmaSiparisID { get; set; }
        public Nullable<double> KdvToplam { get; set; }
        public Nullable<decimal> ToplamIndirim { get; set; }
        public Nullable<int> Vade { get; set; }
        public string OdemeTuru { get; set; }
        public string TeklifDetay { get; set; }
        public Nullable<decimal> GenelToplamTutar { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
    
        public virtual SatinAlmaSiparis SatinAlmaSiparis { get; set; }
    }
}
