//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsProjesi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SatinAlmaSiparis
    {
        public SatinAlmaSiparis()
        {
            this.GiderFatura = new HashSet<GiderFatura>();
            this.Isler = new HashSet<Isler>();
            this.SatinAlmaSiparis_Detay = new HashSet<SatinAlmaSiparis_Detay>();
        }
    
        public int ID { get; set; }
        public Nullable<int> SatinAlmaTeklifID { get; set; }
        public Nullable<int> TedarikciID { get; set; }
        public Nullable<decimal> KdvToplam { get; set; }
        public Nullable<decimal> ToplamTutar { get; set; }
        public Nullable<decimal> ToplamIndirim { get; set; }
        public Nullable<double> Vade { get; set; }
        public string OdemeTuru { get; set; }
        public string TeklifDetay { get; set; }
        public Nullable<decimal> GenelToplamTutar { get; set; }
    
        public virtual ICollection<GiderFatura> GiderFatura { get; set; }
        public virtual ICollection<Isler> Isler { get; set; }
        public virtual SatinAlmaTeklif SatinAlmaTeklif { get; set; }
        public virtual ICollection<SatinAlmaSiparis_Detay> SatinAlmaSiparis_Detay { get; set; }
    }
}
