//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsProjesi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SatisSiparis_Detay
    {
        public int ID { get; set; }
        public Nullable<int> SatisSiparisID { get; set; }
        public Nullable<double> KdvToplam { get; set; }
        public Nullable<double> ToplamIndirim { get; set; }
        public Nullable<double> Vade { get; set; }
        public string OdemeTuru { get; set; }
        public string TeklifDetay { get; set; }
        public Nullable<double> GenelToplam { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
    }
}
