//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsProjesi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SatinAlmaTeklif_Detay
    {
        public int ID { get; set; }
        public Nullable<int> SatinAlmaTeklifID { get; set; }
        public string UrunAdi { get; set; }
        public Nullable<int> Adet { get; set; }
        public Nullable<double> Indirim { get; set; }
        public Nullable<double> BirimFiyat { get; set; }
        public Nullable<double> KdvOran { get; set; }
        public Nullable<double> KdvTutar { get; set; }
        public Nullable<double> ToplamTutar { get; set; }
        public string KalemAdi { get; set; }
        public string Aciklama { get; set; }
    
        public virtual SatinAlmaTeklif SatinAlmaTeklif { get; set; }
    }
}
