//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsProjesi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SatisSiparis
    {
        public SatisSiparis()
        {
            this.GelirFatura = new HashSet<GelirFatura>();
            this.Isler = new HashSet<Isler>();
        }
    
        public int ID { get; set; }
        public Nullable<int> SatisTeklifID { get; set; }
        public Nullable<int> MusteriID { get; set; }
        public Nullable<double> KdvToplam { get; set; }
        public Nullable<double> ToplamTutar { get; set; }
        public Nullable<double> ToplamIndirim { get; set; }
        public Nullable<double> Vade { get; set; }
        public string OdemeTuru { get; set; }
        public string TeklifDetay { get; set; }
        public Nullable<double> GenelToplam { get; set; }
    
        public virtual ICollection<GelirFatura> GelirFatura { get; set; }
        public virtual ICollection<Isler> Isler { get; set; }
        public virtual Musteri Musteri { get; set; }
        public virtual SatisTeklif SatisTeklif { get; set; }
    }
}
