//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsProjesi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SatinAlmaTeklif
    {
        public SatinAlmaTeklif()
        {
            this.SatinAlmaSiparis = new HashSet<SatinAlmaSiparis>();
            this.SatinAlmaTeklif_Detay = new HashSet<SatinAlmaTeklif_Detay>();
        }
    
        public int ID { get; set; }
        public Nullable<int> TedarikciID { get; set; }
        public Nullable<double> KdvToplam { get; set; }
        public Nullable<double> ToplamTutar { get; set; }
        public Nullable<double> ToplamIndirim { get; set; }
        public Nullable<int> Vade { get; set; }
        public Nullable<int> OdemeTuru { get; set; }
        public string TeklifDetay { get; set; }
        public Nullable<double> GenelToplamTutar { get; set; }
        public Nullable<int> Durum { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public Nullable<System.DateTime> TeklifTarih { get; set; }
    
        public virtual ICollection<SatinAlmaSiparis> SatinAlmaSiparis { get; set; }
        public virtual ICollection<SatinAlmaTeklif_Detay> SatinAlmaTeklif_Detay { get; set; }
        public virtual Tedarikci Tedarikci { get; set; }
    }
}
