//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsProjesi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SatisTalep
    {
        public SatisTalep()
        {
            this.SatisTeklif = new HashSet<SatisTeklif>();
        }
    
        public int ID { get; set; }
        public Nullable<int> MusteriID { get; set; }
        public Nullable<int> MusteriAdayID { get; set; }
        public string Konu { get; set; }
        public string Baslik { get; set; }
        public string Icerik { get; set; }
        public string Dokuman { get; set; }
        public string FirmaNotu { get; set; }
        public Nullable<int> Durum { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
    
        public virtual Musteri Musteri { get; set; }
        public virtual MusteriAdaylari MusteriAdaylari { get; set; }
        public virtual ICollection<SatisTeklif> SatisTeklif { get; set; }
    }
}
