//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsProjesi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StokHareketleri
    {
        public int ID { get; set; }
        public Nullable<int> UrunID { get; set; }
        public Nullable<int> StokTip { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public Nullable<int> StokAdet { get; set; }
    
        public virtual UrunHizmet UrunHizmet { get; set; }
    }
}
