//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsProjesi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TedarikciTur
    {
        public TedarikciTur()
        {
            this.Tedarikci = new HashSet<Tedarikci>();
        }
    
        public int ID { get; set; }
        public string Adi { get; set; }
    
        public virtual ICollection<Tedarikci> Tedarikci { get; set; }
    }
}
