//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsProjesi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UrunHizmet
    {
        public UrunHizmet()
        {
            this.Isler = new HashSet<Isler>();
            this.StokHareketleri = new HashSet<StokHareketleri>();
        }
    
        public int ID { get; set; }
        public Nullable<int> KdvID { get; set; }
        public Nullable<int> KategoriID { get; set; }
        public Nullable<int> MiktarTurD { get; set; }
        public Nullable<int> StokDurum { get; set; }
        public Nullable<int> UrunTipID { get; set; }
        public Nullable<double> Fiyat { get; set; }
        public string UrunKodu { get; set; }
        public Nullable<int> StokAdetFinal { get; set; }
        public Nullable<int> DonguselAralik { get; set; }
        public Nullable<double> DonguselFiyat { get; set; }
        public string UrunIcerik { get; set; }
        public string UrunResim { get; set; }
        public string UrunAdi { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
    
        public virtual ICollection<Isler> Isler { get; set; }
        public virtual Kdv Kdv { get; set; }
        public virtual MiktarTur MiktarTur { get; set; }
        public virtual ICollection<StokHareketleri> StokHareketleri { get; set; }
        public virtual UrunHizmetKategori UrunHizmetKategori { get; set; }
    }
}
